app/urls.py
from django.contrib import admin
from django.urls import path,re_path
from app import views

app_name="app"

urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',views.user_login,name='login'),
]

covid19/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import app
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('homepage/',views.homepage, name='homepage'),
    path('',views.index,name='index'),
    path('app/',include("app.urls")),
    path('logout/',views.user_logout,name="logout"),
    path('wish/',views.wish,name='wish'),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User


# Create your models here.
class User_data(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    webpage=models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to='user',blank=True)

    def __str__(self):
        return self.user.username
    

app/forms.py
from app.models import *
from django import forms
class User_Form(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model=User
        fields=('username',"email",'password')
        
class User_data_form(forms.ModelForm):
    class Meta:
        model=User_data
        # fields=('webpage',"profile_pic")
        fields=("profile_pic",)

app/views.py
from django.shortcuts import redirect #"go to the post_detail page for the newly created post"

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.utils import timezone
from app import forms
from django.contrib.auth.decorators import login_required

from django.views.generic import View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView

from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseRedirect
from django.core.mail import send_mail

# Create your views here.
@login_required    
def homepage(request):
    # ctg1=Sslc.objects.all()
    user_name=request.session.get('username',"No User") 
    context = {
        'user_name':user_name
    }
    return render(request,'homepage.html',context)


def register(request):
    register=False
    if request.method=="POST":
        user_form=forms.User_Form(request.POST)
        user_data_form=forms.User_data_form(request.POST,request.FILES)
        if user_form.is_valid() and user_data_form.is_valid():
            user=user_form.save(commit=True)
            user.set_password(user.password)
            user.save()

            user_data=user_data_form.save(commit=False)
            user_data.user=user

            if 'profile_pic' in request.FILES:
                user_data.profile_pic=request.FILES['profile_pic']
            user_data.save()
            register=True
            send_mail("Registration Successful","Thank You For Registering","noreply2user.infotech@gmail.com", \
                [user.email],fail_silently=True) 
     #here we give user.email.............so it will also send to the unknow person who is going to signup here
    else:
        user_form=forms.User_Form()
        user_data_form=forms.User_data_form()
    
    d={'form':user_data_form,'form_user':user_form,'register':register}
    return render(request,'app/register.html',context=d)

def index(request):
    user_name=request.session.get('username',"No User")
    return render(request,'app/base.html',context={'user_name':user_name})


def user_login(request):
    if request.method=="POST":
        username=request.POST.get('username',"")
        password=request.POST.get('password','')
        user=authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                # request.session['username']=username
                request.session['username']=(username) #,user.email
# here we want to display both username&profile_pic after login...username & email are working
# profilepic need to check and need to give the path
                return HttpResponseRedirect(reverse('homepage'))
            else:
                return HttpResponse("Not an Active user")
        else:
            print("Invalid Login")
            return render(request,'app/login.html')
            # return HttpResponse("Invalid Login")
    else:
        return render(request,'app/login.html')
        # return render(request,'homepage.html')


@login_required
def user_logout(request):
    logout(request)
    try:
        del request.session['username']
    except:
        pass
    return HttpResponseRedirect(reverse('index'))
    

@login_required
def wish(request):
    # return HttpResponse("<h1>Hai Mr./Ms. {} </h1>".format(request.session['username']))
    return HttpResponse("<h1>Hai Mr./Ms. {} </h1>")

templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>HOME Page</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>

<body id="bg" style="background-image: url('{% static 'images/bg1.jpg' %}'); background-size: cover; background-position: center; background-attachment: fixed;
width='100%'">
    <!-- Navigation -->
    <!-- Image and text -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'index' %}">
            <img src="{% static 'images/virus.png' %}" width="50" height="50" class="img-thumbnail" alt="">
        </a>
        <a class="navbar-brand" href="#">Covid-19 </a>
        <a class="navbar-brand" href="{% url 'index' %}">Home </a>
        <a class="navbar-brand" href="{% url 'admin:index' %}">Admin</a></li>

        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link text-capitalize">
                        <img src="{% static 'images/student.jpg' %}" width="40" height="40" class="img-thumbnail" alt="Profile" title="View details"> {{ user_name }}</a>
                </li>

            </ul>
        </div>
    </nav>
    {% block body_block %}
    <div id="wrapper">


        <div id="content-wrapper">

            <div class="container-fluid">

                <div class="text-center h3">you have been logged out, Please Login!!
                    <br>
                    <br>
                    <center>
                        <a class="navbar-brand" href="#">
                            <img src="{% static 'images/coronavirus.png' %}" width="300" height="300" class="img-thumbnail" alt="">
                        </a>
                    </center>
                    <a class="btn btn-outline-success" href="{% url 'app:login' %}">login</a> |
                    <a class="btn btn-outline-success" href="{% url 'app:register' %}">Signup</a>

                </div>
            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /.content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>


    <!-- Bootstrap core JavaScript-->
    <script src="{% static '/info/bootstrap/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static '/info/bootstrap/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static '/info/bootstrap/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static '/info/bootstrap/js/sb-admin.min.js' %}"></script>

</body>
<!-- Footer --><br><br><br><br><br><br><br><br>
<footer>
    <div class="footer-copyright text-center py-3">© 2020 Developed by:
        <a href="https://www.instagram.com/suresh_tumu/"> sureshtumu</a>
    </div>
</footer>
{% endblock body_block %}

templates/app/login.html
{% extends 'app/base.html' %}{% load static %} {% block body_block %}
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6 lt8"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7 lt8"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8 lt8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->

<head>
    <meta charset="UTF-8" />
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">  -->
    <title>Login and Registration Form with HTML5 and CSS3</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Login and Registration Form with HTML5 and CSS3" />
    <meta name="keywords" content="html5, css3, form, switch, animation, :target, pseudo-class" />
    <meta name="author" content="Codrops" />
    <!-- <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/demo.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate-custom.css' %}" />
</head>

<body>
    <div class="container">
        <header>
            <nav class="codrops-demos">
                <span>click <strong>"Login"</strong>or <strong>"Joinus"</strong></span>
            </nav>
        </header>
        <section>
            <div id="container_demo">
                <!-- hidden anchor to stop jump http://www.css3create.com/Astuce-Empecher-le-scroll-avec-l-utilisation-de-target#wrap4  -->
                <a class="hiddenanchor" id="toregister"></a>
                <a class="hiddenanchor" id="tologin"></a>
                <div id="wrapper">
                    <div id="login" class="animate form">
                        <!-- <form action="mysuperscript.php" autocomplete="on"> -->
                        <form action="{% url 'app:login' %}" method='POST'>{% csrf_token %}
                            <h1>Log in</h1>
                            <p>
                                <label for="username" class="uname" data-icon="u"> Your email or username </label>
                                <input id="username" name="username" required="required" type="text" placeholder="myusername or mymail@mail.com" />
                            </p>
                            <p>
                                <label for="password" class="youpasswd" data-icon="p"> Your password </label>
                                <input id="password" name="password" required="required" type="password" placeholder="eg. X8df!90EO" />
                            </p>
                            <p class="keeplogin">
                                <input type="checkbox" name="loginkeeping" id="loginkeeping" value="loginkeeping" />
                                <label for="loginkeeping">Keep me logged in</label>
                            </p>
                            <p class="login button">
                                <input type="submit" value="Login" />
                            </p>
                            <p class="change_link">
                                Not a member yet ?
                                <a href="{% url 'app:register' %}" class="to_register">Join us</a>
                            </p>
                        </form>
                    </div>

                </div>
            </div>
        </section>
    </div>
</body>
<!-- Footer -->
<footer>
    <div class="footer-copyright text-center py-3">© 2019 Developed by:
        <a href="https://www.instagram.com/suresh_tumu/"> sureshtumu</a>
    </div>
</footer>

</html>
{% endblock body_block %}

templates/app/loginReg.html
{% load static%}
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6 lt8"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7 lt8"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8 lt8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->

<head>
    <meta charset="UTF-8" />
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">  -->
    <title>Login and Registration Form with HTML5 and CSS3</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Login and Registration Form with HTML5 and CSS3" />
    <meta name="keywords" content="html5, css3, form, switch, animation, :target, pseudo-class" />
    <meta name="author" content="Codrops" />
    <!-- <link rel="shortcut icon" href="../favicon.ico"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/demo.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate-custom.css' %}" />
</head>

<body>
    <div class="container">
        <header>
            <nav class="codrops-demos">
                <span>click <strong>"Login"</strong>or <strong>"Joinus"</strong></span>
            </nav>
        </header>
        <section>
            <div id="container_demo">
                <!-- hidden anchor to stop jump http://www.css3create.com/Astuce-Empecher-le-scroll-avec-l-utilisation-de-target#wrap4  -->
                <a class="hiddenanchor" id="toregister"></a>
                <a class="hiddenanchor" id="tologin"></a>
                <div id="wrapper">
                    <div id="login" class="animate form">
                        <form action="{% url 'app:login' %}" method='POST'>{% csrf_token %}
                            <h1>Log in</h1>
                            <p>
                                <label for="username" class="uname" data-icon="u"> Your email or username </label>
                                <input id="username" name="username" required="required" type="text" placeholder="myusername or mymail@mail.com" />
                            </p>
                            <p>
                                <label for="password" class="youpasswd" data-icon="p"> Your password </label>
                                <input id="password" name="password" required="required" type="password" placeholder="eg. X8df!90EO" />
                            </p>
                            <p class="keeplogin">
                                <input type="checkbox" name="loginkeeping" id="loginkeeping" value="loginkeeping" />
                                <label for="loginkeeping">Keep me logged in</label>
                            </p>
                            <p class="login button">
                                <input type="submit" value="Login" />
                            </p>
                            <p class="change_link">
                                Not a member yet ?
                                <a href="#toregister" class="to_register">Join us</a>
                            </p>
                        </form>
                    </div>
                    {% if register %}
                    <h1>Thanks for registering</h1>
                    <h1>please click here to login</h1><a class="nav-link" href="{% url 'app:login' %}">login</a> {% else %}
                    <div id="register" class="animate form">
                        <form method="POST" enctype="multipart/form-data">
                            <h1> Sign up </h1>
                            {% csrf_token %} {{form_user.as_p}} {{form.as_p}}
                            <input type="submit" value="Submit">
                            <p class="change_link">
                                Already a member ?
                                <a href="#tologin" class="to_register"> Go and log in </a>
                            </p>
                            {% endif %}
                        </form>
                    </div>

                </div>
            </div>
        </section>
    </div>
</body>

</html>

templates/app/register.html
{% extends 'app/base.html' %}{% load static %} {% block body_block %}
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6 lt8"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7 lt8"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8 lt8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->

<head>
    <meta charset="UTF-8" />
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">  -->
    <title>Login and Registration Form with HTML5 and CSS3</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Login and Registration Form with HTML5 and CSS3" />
    <meta name="keywords" content="html5, css3, form, switch, animation, :target, pseudo-class" />
    <meta name="author" content="Codrops" />
    <!-- <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/demo.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate-custom.css' %}" />
</head>

<body>
    <div class="container">
        <header>
            <nav class="codrops-demos">
                <span>click <strong>"Login"</strong>or <strong>"Joinus"</strong></span>
            </nav>
        </header>
        <section>
            <div id="container_demo">
                <!-- hidden anchor to stop jump http://www.css3create.com/Astuce-Empecher-le-scroll-avec-l-utilisation-de-target#wrap4  -->
                <a class="hiddenanchor" id="toregister"></a>
                <a class="hiddenanchor" id="tologin"></a>
                <div id="wrapper">
                    <div id="login" class="animate form">
                        {% if register %}
                        <h1>Thanks for registering</h1>
                        <h1>please click below to login</h1>
                        <a class="btn btn-outline-success" href="{% url 'app:login' %}">login</a> {% else %}
                        <h1> Sign up </h1>
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %} {{form_user.as_p}} {{form.as_p}}
                            <p class="signin button">
                                <input type="submit" value="Sign up" />
                            </p>
                            <p class="change_link">
                                Already a member ?
                                <a href="{% url 'app:login' %}" class="to_register"> Go and log in </a>
                            </p>
                        </form>
                    </div>

                </div>
            </div>
        </section>
    </div>
</body>
<!-- Footer -->
<footer>
    <div class="footer-copyright text-center py-3">© 2020 Developed by:
        <a href="https://www.instagram.com/suresh_tumu/"> sureshtumu</a>
    </div>
</footer>

</html>{% endif %}{% endblock body_block %}

templates/homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Library</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>

<body id="bg" style="background-image: url('{% static 'images/bg1.jpg' %}'); background-size: cover; background-position: center; background-attachment: fixed;
width='100%'">
    <!-- Navigation -->
    <!-- Image and text -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'homepage' %}">
            <img src="{% static 'images/coronavirus.png' %}" width="50" height="50" class="img-thumbnail" alt="">
        </a>
        <a class="navbar-brand" href="{% url 'homepage' %}">Covid-19</a>
        <a class="navbar-brand" href="{% url 'homepage' %}">Home </a>
        <a class="navbar-brand" href="{% url 'admin:index' %}">Admin</a></li>

        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <!--
                <li class="nav-item">
                    <a class="navbar-brand" href="{% url 'index' %}">
                        <img src="{% static 'info/images/student.jpg' %}" width="50" height="50" class="img-thumbnail" alt="Profile" title="View details">
                    </a>
                </li>-->
                <li class="nav-item">
                    <a class="nav-link text-capitalize">
                        <img src="{% static 'images/student.jpg' %}" width="40" height="40" class="img-thumbnail" alt="Profile" title="View details"> {{ user_name }}</a>
                </li>
                <li class="nav-item">
                    <!-- <a class="nav-link" href="{% url 'logout' %}" data-toggle="modal" data-target="#logoutModal"> Logout</a> -->
                    <a class="nav-link" href="{% url 'logout' %}" data-toggle="modal" data-target="#logoutModal"> Logout</a>
                </li>
            </ul>
        </div>
    </nav>

    <!-- Page Content -->
    <div class="container">
        <!-- Jumbotron Header -->
        <header class="jumbotron my-4">
            <!-- <h1 class="display-3 text-capitalize">Welcome </h1> -->
            <h1 class="display-3 text-capitalize">Welcome</h1>
            <!-- <div class='jumbotron'>
                <h1>Welcome To Library </h1>
                {{user_name}} has loged in
            </div> -->
            <p>
                <strong>{{user_name}} </strong>has loged in</p>
        </header>


        <br> {% block content %}

        <!-- Example single danger button -->
        <div class="row text-center">

            <div class="col-lg-3 col-md-6 mb-4">
                <div class="card">
                    <div class="card h-100">
                    <img src="{% static 'images/IFC.png' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h4 class="card-title">{{ctg1}} </h4>
                        <p class="card-text">Text Area.</p>
                    </div>
                    <div class="card-footer">
                        <a href="https://www.mygov.in/covid-19/" class="btn btn-outline-success stretched-link">Click here>></a>
                    </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mb-4">
                <div class="card">
                    <div class="card h-100">
                    <img src="{% static 'images/opengraph.png' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h4 class="card-title">{{ctg2}} </h4>
                        <p class="card-text">Text Area.</p>
                    </div>
                    <div class="card-footer">
                        <a href="https://www.covidvisualizer.com/" class="btn btn-outline-success stretched-link">Click here>></a>
                    </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mb-4">
                <div class="card">

                    <div class="card-body">
                        <h4 class="card-title">{{ctg3}} </h4>
                        <p class="card-text">Text Area.</p>
                    </div>
                    <div class="card-footer">
                        <a href="#" class="btn btn-outline-success stretched-link">click here>><span>({{ c3 }})</span></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mb-4">
                <div class="card">

                    <div class="card-body">
                        <h4 class="card-title">{{ctg4}} </h4>
                        <p class="card-text">Text Area.</p>
                    </div>
                    <div class="card-footer">
                        <a href="#" class="btn btn-outline-success stretched-link">click here>><span>({{ c4 }})</span></a>
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}
    </div>
</body>
<!-- Footer -->
<footer>
    <div class="footer-copyright text-center py-3">© 2020 Developed by:
        <a href="https://www.instagram.com/suresh_tumu/"> sureshtumu</a>
    </div>
</footer>
</html>